### ایجاد مشتری
POST http://localhost:3000/api/customers
Content-Type: application/json

{
  "name": "Ali Ahmadi",
  "phoneNumber": "09123456789",
  "cardNumber": "6037991874465128",
  "description": "TozihatTozihatTozihatTozihat"
}


### ایجاد تراکنش
POST http://localhost:3000/api/transactions
Content-Type: application/json

{
  "customerId": 17,
  "currency": "TOMAN",
  "amount": -12000000,
  "note": "باید 12 تومن بزم به کارت"
}


### دریافت مشتری
GET http://localhost:3000/api/customers/17


### تاریخچه تراکنش‌ها
GET http://localhost:3000/api/transactions/customer/1?currency=USD